flow/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^api/v1/', include('workflow.urls')),
]

workflow/models.py
from django.db import models

# Create your models here.


class BaseModel(models.Model):
    id = models.AutoField(primary_key=True)
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    update_time = models.DateTimeField(auto_now=True, verbose_name='更新时间')
    is_delete = models.BooleanField(default=False, verbose_name='删除标记')

    class Meta:
        abstract = True


class Ticket(BaseModel):
    ticket_name = models.CharField(max_length=50, verbose_name='工单名称', unique=True, null=False, db_index=True)
    ticket_id = models.CharField(max_length=50, verbose_name='工单id', unique=True, db_index=True)
    ticket_type = models.ForeignKey('TicketType', verbose_name='工单类型', db_index=True, on_delete=models.PROTECT)
    current_node = models.ForeignKey('Node', verbose_name='当前节点', on_delete=models.PROTECT)
    ticket_status = models.IntegerField(verbose_name='工单状态', choices=[
        (1, '申请'),
        (2, '处理中'),
        (3, '已处理'),
        (4, '已驳回')
    ])
    applicant = models.CharField(max_length=50, default='', verbose_name='申请人', db_index=True)

    class Meta:
        verbose_name = '工单表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.ticket_name


class TicketType(BaseModel):
    type_name = models.CharField(max_length=50, verbose_name='工单类型', null=False, db_index=True)
    flow_id = models.CharField(max_length=50, verbose_name='流程id', null=False)

    class Meta:
        verbose_name = '工单类型表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.type_name


class Role(BaseModel):
    username = models.CharField(max_length=50, verbose_name='关联用户名', null=False, db_index=True)
    node_id = models.ForeignKey('Node', on_delete=models.PROTECT, verbose_name='节点id')

    class Meta:
        unique_together = ("username", "node_id")
        verbose_name = '角色表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.username


class Node(BaseModel):
    name = models.CharField(max_length=50, verbose_name='节点名称', null=False, db_index=True)
    # parent_node = models.ForeignKey("self", verbose_name='父节点', null=True, on_delete=models.PROTECT, blank=True)
    # child_node = models.ForeignKey("self", verbose_name='子节点', null=True, on_delete=models.PROTECT, blank=True)

    class Meta:
        verbose_name = '节点表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Flow(BaseModel):
    name = models.CharField(max_length=50, verbose_name='流程名称', null=False, db_index=True)
    flow_id = models.ForeignKey('TicketType', on_delete=models.PROTECT, verbose_name='审批流程')
    node_id = models.ForeignKey('Node', on_delete=models.PROTECT, verbose_name='节点id', related_name='node_id')
    child_node_id = models.ForeignKey('Node', on_delete=models.PROTECT, verbose_name='子节点id', related_name='child_node_id', blank=True, null=True)

    class Meta:
        verbose_name = '流程表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Ticket_detail(BaseModel):
    ticket_id = models.ForeignKey('Ticket', on_delete=models.PROTECT, verbose_name='工单id')
    ticket_detail = models.TextField(verbose_name='工单信息')

    class Meta:
        verbose_name = '工单详情表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.ticket_id.ticket_name


class Participation_info(BaseModel):
    ticket_id = models.ForeignKey('Ticket', on_delete=models.PROTECT, verbose_name='工单id')
    node_id = models.ForeignKey('Node', on_delete=models.PROTECT, verbose_name='节点id')
    participant = models.CharField(max_length=50, verbose_name='处理人', null=False)
    suggestion = models.TextField(verbose_name='处理意见', blank=True)
    status = models.BooleanField(verbose_name='处理结果', default=True)

    class Meta:
        verbose_name = '处理情况表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.ticket_id.ticket_name

templates/allticket.html
{% extends "base_admin.html" %}
{% block title %}所有工单{% endblock %}
{% block active_all %}active{% endblock active_all %}
{% block csrf %}{% endblock csrf %}
{% block method %}get{% endblock method %}
{% block input %}
    <span class="input-group-addon">搜索</span>
    <input type="text" class="form-control"  name="q" style="width: 500px;" placeholder="请输入关键字">
{% endblock input %}
{% block table %}
    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <th>工单ID</th>
                <th>申请人</th>
                <th>工单名称</th>
                <th>工单类型</th>
                <th>当前节点</th>
                <th>工单状态</th>
                <th>提交时间</th>
                <th>变更时间</th>
                <th>工单详情</th>
            </tr>
        </thead>
        <tbody>
        {% for tic in allpage %}
        <tr>
            <td>{{ tic.ticket_id }}</td>
            <td>{{ tic.applicant }}</td>
            <td>{{ tic.ticket_name }}</td>
            <td>{{ tic.ticket_type }}</td>
            <td>{{ tic.current_node }}</td>
            <td>{{ tic.get_ticket_status_display }}</td>
            <td>{{ tic.create_time }}</td>
            <td>{{ tic.update_time }}</td>
            <td><a href="{% url "ticket_detail" ticket_id=tic.ticket_id %}">详情</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}
{% block button %}
    <div class="butt_r">
        <input type="submit" class="btn btn-info btn-fill" value="提交" {{ disable }}/>
    </div>
{% endblock button %}
{% block pages %}
<div class="word">
     <ul class="pagination pagination-sm">
        {% if allpage.has_previous %}
        <li><a href="{{ allpage.previous_page_number }}">&laquo;</a></li>
                {% endif %}
            {% for pindex in pages %}
                {% if pindex == allpage.number %}
                    <li><a href="">{{ pindex }}</a></li>
                {% else %}
                    <li><a href="{{ pindex }}">{{ pindex }}</a></li>
                {% endif %}
            {% endfor %}
                {% if allpage.has_next %}
                <li><a href="{{ allpage.next_page_number }}">&raquo;</a></li>
                 {% endif %}
            </ul>
        </ul>
</div>
{% endblock pages %}

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="renderer" content="webkit">

    <title>Flow</title>

    <link rel="shortcut icon" href="/static/img/facio.ico" type="image/x-icon">
    {% include 'link_css.html' %}
    {% include 'head_script.html' %}
    {% block self_head_css_js %} {% endblock %}
</head>

<body>

    <div id="wrapper">
    <nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            {% include 'nav_li_profile.html' %}
            <li id="juser" class="{% block nav_apply %}{% endblock %}">
                <a href="#"><i class="fa fa-upload"></i> <span class="nav-label">业务申请</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li class="{% block active_apply %}{% endblock %}"><a href="{% url 'apply' %}">工单申请</a></li>
                </ul>
            </li>
            <li id="juser" class="{% block nav_ticket %}{% endblock %}">
                <a><i class="fa fa-inbox"></i> <span class="nav-label">我的工单</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li class="{% block active_workflow_myticket %}{% endblock %}"><a href="{% url 'list_myticket' ticstatus=2 page=1 %}">正在进行</a></li>
                    <li class="{% block active_workflow_ticket_done %}{% endblock %}"><a href="{% url 'list_myticket' ticstatus=3 page=1 %}">已结束</a></li>
                    <li class="{% block active_workflow_ticket_rejected %}{% endblock %}"><a href="{% url 'list_myticket' ticstatus=4 page=1 %}">已驳回</a></li>
                    <li class="{% block active_workflow_ticket_pending %}{% endblock %}"><a href="{% url "ticket_pending" page=1 %}">待审批</a></li>
                    <li class="{% block active_workflow_ticket_approved %}{% endblock %}"><a href="{% url "ticket_approved" page=1 %}">已审批</a></li>
                </ul>
            </li>
        </ul>

    </div>
</nav>

{#    {% block nav %}{% endblock %}#}
{#        {% include 'newdisplay/nav.html' %}#}
        <div id="page-wrapper" class="gray-bg">
            <div class="row border-bottom">
                {% include 'nav_bar_header.html' %}
            </div>
            {% block content %}
                {% block submit %}
                    <div class="content">
                        <form action="{% block action %}{% endblock action %}" method="{% block method %}post{% endblock method %}" name="insert">
                        {% block csrf %}{% csrf_token %}{% endblock csrf %}
                        <div class="exp">
                            <label>
                                <div id="input-group" class="input-group">
                                    {% block input %}{% endblock input %}
                                </div><br>
                            </label>
                        </div>
                        {% block graph %}{% endblock graph %}
                        <div class="container-fluid">
                            <div class="col-md-12">
                                <div class="card">
                                    <div class="header">
                                        {% block table_header %}{% endblock table_header %}
                                    </div>
                                    <div class="content table-responsive table-full-width" {{ hidden }}>
                                    {% block table %}{% endblock table %}
                                    </div>
                                    {% block pages %}{% endblock pages %}
                                    <div class="butt">
                                        {% block button %}
                                            <div class="butt_r">
                                                <input type="submit" class="btn btn-info btn-fill" value="提交" onclick="return confirm('Are you sure? MAN?')" {{ disable }}/>
                                            </div>
                                            <div class="butt_l">
                                                <input type="reset"  class="btn butt_c" οnclick="formReset()" value="重置">
                                            </div>
                                        {% endblock button %}
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="name"></label>
                                <textarea class="form-control" rows="3" disabled="disabled" style="resize: none">{{ data }}{{ request.session.data }}</textarea>
                            </div>
                        </div>
                        </form>
                    </div>
                {#</div>#}
                {% endblock %}
            {% endblock %}

{#            {% include 'newdisplay/footer.html' %}#}
        </div>
    </div>

</body>
    {% include 'foot_script.html' %}
    {% block self_footer_js %}
        <script src="/static/js/new_file.js"></script>
    {% endblock %}
</html>

templates/flow_edit.html
{% extends "base_admin.html" %}
{% block title %}流程配置-{{ ticket_type.type_name }}{% endblock %}
{% block active_flow %}active{% endblock %}
{% block input %}
    <span class="input-group-addon">工单类型</span>
    <input type="text" class="form-control region" name="ticket_type_name" required="required" style="width: 200px;" placeholder="工单类型" value="{{ ticket_type.type_name }}" disabled="disabled">
{% endblock input %}
{% block table_header %}
    <h4 class="title">工单流程: </h4><br>
{% endblock table_header %}
{% block table %}
    <div class="exp request_input">
        <datalist id="nodelist">
            {% for node in nodes %}
                <option value="{{ node }}">
            {% endfor %}
        </datalist>
        {% for flow in flows %}
            {% if forloop.counter == 1 %}
                <div class="input-group">
                <input type="text" class="form-control rds_type" name="nodes" required="required" style="width: 100px;" placeholder="节点" value="{{ flow.node_id.name }}" readonly="readonly">
                <input type="button" value="添加" class="add-row btn btn-info btn-fill" onclick="addrow();">
{#            <input type="button" value="删除" class="del_row btn butt_c">#}
                </div>
            {% else %}
                <div class="input-group">
                <input type="text" class="form-control rds_type" name="nodes" required="required" list="nodelist" style="width: 100px;" placeholder="节点" value="{{ flow.node_id.name }}" autocomplete="off">
    {#            <input type="button" value="添加" class="add-row btn btn-info btn-fill" onclick="addrow();">#}
                <input type="button" value="删除" class="del_row btn butt_c">
{#            <input type="button" value="删除" class="del_row btn butt_c">#}
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}
{% block script %}
    <script>
        $('.request_input').on('click', '.del_row', function () {
            $(this).parent().remove()
        })

        $('.request_input').on('blur', '.rds_type', function () {
            rdstype = $(this).val()
            $('.meal').attr("list", rdstype)
            $(this).next().attr("list", rdstype)
        })
        function addrow() {
            var newline = $(
                '<div class=\"input-group\">\n' +
                    '<input type=\"text\" class=\"form-control rds_type\" name=\"nodes\" required=\"required\" list=\"nodelist\" style=\"width: 100px;\" placeholder=\"节点\" autocomplete=\"off\">\n' +
                    {#'<input type=\"button\" value=\"添加\" class=\"add-row btn btn-info btn-fill\" onclick=\"addrow();\">' +#}
                    '<input type=\"button\" value=\"删除\" class=\"del_row btn butt_c\">\n' +
                '</div>'
            );
            $('.request_input').append(newline);
        }
    </script>
{% endblock script %}

templates/flow_list.html
{% extends "base_admin.html" %}
{% block title %}流程列表{% endblock %}
{% block active_flow %}active{% endblock %}
{% block input %}
    <input type="button" class="btn btn-info btn-fill" name="add-new" onclick="location.href='{% url "new_flow" %}'" value="新建工单流程">
{% endblock %}
{% block table %}
    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <th>流程名称(关联工单类型)</th>
                <th>创建时间</th>
                <th>流程详情</th>
            </tr>
        </thead>
        <tbody>
        {% for ticket_type in ticket_types %}
        <tr>
            <td>{{ ticket_type.type_name }}</td>
            <td>{{ ticket_type.create_time }}</td>
            <td><a href="{% url "flows_config" ticket_type_id=ticket_type.id %}">详情</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}
{% block button %}{% endblock button %}

templates/flow_new.html
{% extends "base_admin.html" %}
{% block title %}新建工单流程{% endblock %}
{% block active_flow %}active{% endblock %}
{% block input %}
    <span class="input-group-addon">工单类型</span>
    <input type="text" class="form-control region" name="ticket_type_name" required="required" style="width: 200px;" placeholder="工单类型">
{% endblock input %}
{% block table_header %}
    <h4 class="title">工单流程: </h4><br>
{% endblock table_header %}
{% block table %}
    <div class="exp request_input">
        <datalist id="nodelist">
            {% for node in nodes %}
                <option value="{{ node }}">
            {% endfor %}
        </datalist>
        <div class="input-group">
            <input type="text" class="form-control rds_type" name="nodes" required="required" style="width: 100px;" placeholder="节点" value="申请">
            <input type="button" value="添加" class="add-row btn btn-info btn-fill" onclick="addrow();">
        </div>
    </div>
{% endblock %}
{% block self_footer_js %}
    <script>
        $('.request_input').on('click', '.del_row', function () {
            $(this).parent().remove()
        })

        $('.request_input').on('blur', '.rds_type', function () {
            rdstype = $(this).val()
            $('.meal').attr("list", rdstype)
            $(this).next().attr("list", rdstype)
        })
        function addrow() {
            var newline = $(
                '<div class=\"input-group\">\n' +
                    '<input type=\"text\" class=\"form-control rds_type\" name=\"nodes\" required=\"required\" list=\"nodelist\" style=\"width: 100px;\" placeholder=\"节点\" autocomplete=\"off\">\n' +
                    '<input type=\"button\" value=\"删除\" class=\"del_row btn butt_c\">\n' +
                '</div>'
            );
            $('.request_input').append(newline);
        }
    </script>
{% endblock %}

templates/head_script.html
<script src="/static/js/jquery-2.1.1.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/base.js"></script>

<!-- pop windows -->
<script src="/static/js/jquery.colorbox.js"></script>

<!-- validator js -->
<script src="/static/js/validator/jquery.validator.js"></script>
<script src="/static/js/validator/zh_CN.js"></script>
<script src="/static/js/datapicker/bootstrap-datepicker.js"></script>
<script src="/static/js/vue.js"></script>
<script src="/static/js/index.js"></script>
<script src="/static/js/new_file.js"></script>
<link rel="stylesheet" type="text/css" href="/static/css/flow.css"/>

templates/index.html
{% extends 'base.html' %}
{% block title %}Title{% endblock %}
{% block nav_apply %}active{% endblock %}
{% block active_apply %}active{% endblock %}

{% block input %}
    <span class="input-group-addon">Title</span>
    <input type="text" class="form-control" name="title" required="required" style="width: 500px;" placeholder="TODO" autocomplete="off" {{ disable|safe }}>
    <input type="text" class="form-control" name="type" required="required" style="width: 150px;" placeholder="TYPE" autocomplete="off">
{% endblock %}

templates/link_css.html
<link href="/static/css/bootstrap.min.css" rel="stylesheet">
<link href="/static/font-awesome/css/font-awesome.css" rel="stylesheet">
<link href="/static/css/plugins/iCheck/custom.css" rel="stylesheet">
<link href="/static/css/animate.css" rel="stylesheet">
<link href="/static/css/style.css" rel="stylesheet">
<link href="/static/css/colorbox.css" rel="stylesheet">
<link href="/static/css/vaildator/jquery.validator.css" rel="stylesheet">
<link href="/static/css/magnific/magnific-popup.css" rel="stylesheet">
<link href="/static/css/plugins/fullcalendar/fullcalendar.css" rel="stylesheet">
<link href="/static/css/plugins/dropzone/basic.css" rel="stylesheet">
<link href="/static/css/plugins/dropzone/dropzone.css" rel="stylesheet">

templates/myticket.html
{% extends 'pagenation.html' %}
{% block nav_ticket %}active{% endblock nav_ticket %}
{% block csrf %}{% endblock csrf %}
{% block method %}get{% endblock method %}
{% block input %}
    <span class="input-group-addon">搜索</span>
    <input type="text" class="form-control"  name="q" style="width: 500px;" placeholder="请输入关键字">
{% endblock input %}
{% block active_workflow_myticket %}
    {% if ticstatus == 2 %}
        active
    {% endif %}
{% endblock %}
{% block active_workflow_ticket_done %}
    {% if ticstatus == 3 %}
        active
    {% endif %}
{% endblock %}
{% block active_workflow_ticket_rejected %}
    {% if ticstatus == 4 %}
        active
    {% endif %}
{% endblock %}


{% block table %}
    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <th>工单ID</th>
                <th>申请人</th>
                <th>工单名称</th>
                <th>工单类型</th>
                <th>当前节点</th>
                <th>工单状态</th>
                <th>提交时间</th>
                <th>变更时间</th>
                <th>工单详情</th>
            </tr>
        </thead>
        <tbody>
        {% for tic in allpage %}
        <tr>
            <td>{{ tic.ticket_id }}</td>
            <td>{{ tic.applicant }}</td>
            <td>{{ tic.ticket_name }}</td>
            <td>{{ tic.ticket_type }}</td>
            <td>{{ tic.current_node }}</td>
            <td>{{ tic.get_ticket_status_display }}</td>
            <td>{{ tic.create_time }}</td>
            <td>{{ tic.update_time }}</td>
            <td><a href="{% url "ticket_detail" ticket_id=tic.ticket_id %}">详情</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}
{% block button %}
    <div class="butt_r">
        <input type="submit" class="btn btn-info btn-fill" value="提交" {{ disable }}/>
    </div>
{% endblock button %}

templates/role_new.html
{% extends "base_admin.html" %}
{% block title %}新建角色{% endblock %}
{% block active_role %}active{% endblock %}

{% block input %}
    <span class="input-group-addon">角色名称</span>
    <input type="text" class="form-control region" name="role_name" required="required" style="width: 200px;" placeholder="角色名称">
{% endblock input %}

templates/ticket_approve_done.html
{% extends "pagenation.html" %}
{% block nav_ticket %}active{% endblock nav_ticket %}
{% block active_workflow_ticket_approved %}active{% endblock %}
{% block csrf %}{% endblock csrf %}
{% block method %}get{% endblock method %}
{% block input %}
    <span class="input-group-addon">搜索</span>
    <input type="text" class="form-control"  name="q" style="width: 500px;" placeholder="请输入关键字">
{% endblock input %}

{% block table %}
    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <th>工单ID</th>
                <th>申请人</th>
                <th>工单名称</th>
                <th>工单类型</th>
                <th>当前节点</th>
                <th>工单状态</th>
                <th>提交时间</th>
                <th>变更时间</th>
                <th>工单详情</th>
            </tr>
        </thead>
        <tbody>
        {% for tic in allpage %}
        <tr>
            <td>{{ tic.ticket_id }}</td>
            <td>{{ tic.applicant }}</td>
            <td>{{ tic.ticket_name }}</td>
            <td>{{ tic.ticket_type }}</td>
            <td>{{ tic.current_node }}</td>
            <td>{{ tic.get_ticket_status_display }}</td>
            <td>{{ tic.create_time }}</td>
            <td>{{ tic.update_time }}</td>
            <td><a href="{% url "ticket_detail" ticket_id=tic.ticket_id %}">详情</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}
{% block button %}
    <div class="butt_r">
        <input type="submit" class="btn btn-info btn-fill" value="提交" {{ disable }}/>
    </div>
{% endblock button %}

templates/ticket_detail.html
{% extends "base_ticket.html" %}
{% block nav_ticket %}active{% endblock nav_ticket %}
{% block title %}工单详情-{{ ticket.ticket_name }}{% endblock %}
{% block active_workflow_myticket %}active{% endblock %}
{% block input %}
    <h4 class="title">项目：{{ ticket.project }}</h4>
{% endblock input %}
{% block table_header %}
    {% if ticket.ticket_status == 2 %}
        <h4 class="current_user">当前可审批人：{{ ticket.current_user }}</h4>
    {% endif %}
    <h4 class="ticid title" hidden="hidden">{{ ticket.ticket_id }}</h4>
    <br>
{% endblock %}
{% block table %}
    {% if ticket.ticket_type.type_name == 'type_you_define' %}
        <p>{{ ticket.ticket_name }}</p>
    {% endif %}
{% endblock %}
{% block button %}
{% endblock button %}
{% block table2 %}
{#    {{ nodes }}#}
    <div id="tiket_flow">
    {% if ticket.ticket_status == 2 %}
        <el-steps :active="{{ ticket.currstatuscount }}" align-center>
        {% for node in nodes %}
            {% if node.status.participant %}
            <el-step title="{{ node.name }}:{{ node.status.participant }}" description="处理意见: {{ node.status.suggestion }}"></el-step>
            {% else %}
            <el-step title="{{ node.name }}" description="{{ node.status.suggestion }}"></el-step>
            {% endif %}
        {% endfor %}
    {% else %}
        <el-steps :active="{{ nodes | length }}" align-center>
        {% for node in nodes %}
        <el-step title="{{ node.node_id.name }}:{{ node.participant }}" description="处理意见: {{ node.suggestion }}"></el-step>
        {% endfor %}
    {% endif %}
        </el-steps>
    </div>
{% endblock table2 %}

{% block self_footer_js %}
    <script>
    new Vue({
      el: '#tiket_flow',
      data: function() {
        return { visible: false }
      }
    })
    </script>
    <script src="/static/js/vue.js"></script>
    <script src="/static/js/index.js"></script>
    <script src="/static/js/new_file.js"></script>
    <link rel="stylesheet" type="text/css" href="/static/css/flow.css"/>
{% endblock self_footer_js %}

templates/ticket_detail_approve.html
{% extends "ticket_detail.html" %}
{% block nav_ticket %}active{% endblock nav_ticket %}
{% block title %}工单审批-{{ ticket.ticket_name }}{% endblock %}
{% block table1 %}
    {% if ticket.ticket_status == 2 %}
        <input type="text" class="form-control suggestion"  name="suggestion" style="width: 500px;" placeholder="处理意见" {{ disable|safe }}>
    {% endif %}
{% endblock table1 %}
{% block table_header %}
    <h4 class="ticid title" hidden="hidden">{{ ticket.ticket_id }}</h4>
    <br>
{% endblock table_header %}
{% block button %}
    {% if ticket.ticket_status == 2 %}
    <div class="butt_r">
        <input type="button" class="btn btn-info btn-fill submit_approve" value="提交" name="approve" onclick="return confirm('Are you sure? MAN?')"/>
    </div>
    <div class="butt_l">
        <input type="button"  class="btn btn-info btn-fill reject_approve" value="驳回" name="reject" onclick="return confirm('Are you sure? MAN?')"/>
    </div>
    {% endif %}
{% endblock button %}
{% block self_footer_js %}
    <script src="/static/js/vue.js"></script>
    <script src="/static/js/index.js"></script>
    <script src="/static/js/new_file.js"></script>
    <link rel="stylesheet" type="text/css" href="/static/css/flow.css"/>
    {% if ticket.ticket_status == 2 %}
    <script>
        $('.submit_approve').click(function () {
            ticket_id = $('.ticid').text()
            suggestion = $('.suggestion').val()
            csrf = $('input[name="csrfmiddlewaretoken"]').val()
            {#params = {'ticket_id': ticket_id, 'csrfmiddlewaretoken': csrf}#}
            params = {'ticket_id': ticket_id, 'approve': 0, 'suggestion': suggestion}
            $.ajax({
                url: '{% url "ticket_update" %}',
                type: "put",
                headers: {"X-CSRFtoken": csrf},
                data: params,
                dataType: "json",
                success: function (data) {
                    if (data.Status == 0) {
                        alert(data.Result)
                        location.reload();
                    } else {
                        alert(data.Result)
                    }
                }
            })
        })
        $('.reject_approve').click(function () {
            ticket_id = $('.ticid').text()
            suggestion = $('.suggestion').val()
            csrf = $('input[name="csrfmiddlewaretoken"]').val()
            {#params = {'ticket_id': ticket_id, 'csrfmiddlewaretoken': csrf}#}
            params = {'ticket_id': ticket_id, 'approve': 1, 'suggestion': suggestion}
            $.ajax({
                url: '{% url "ticket_update" %}',
                type: "put",
                headers: {"X-CSRFtoken": csrf},
                data: params,
                dataType: "json",
                success: function (data) {
                    if (data.Status == 0){
                    alert(data.Result)
                    location.reload();
                    }
                    else {
                        alert(data.Result)
                    }
                }
            })
        })
    </script>
    {% endif %}
{% endblock self_footer_js %}

templates/ticket_pending.html
{% extends 'pagenation.html' %}
{% block nav_ticket %}active{% endblock nav_ticket %}
{% block active_workflow_ticket_pending %}active{% endblock %}
{% block csrf %}{% endblock csrf %}
{% block method %}get{% endblock method %}
{% block input %}
    <span class="input-group-addon">搜索</span>
    <input type="text" class="form-control"  name="q" style="width: 500px;" placeholder="请输入关键字">
{% endblock input %}
{% block table %}
    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <th>工单ID</th>
                <th>申请人</th>
                <th>工单名称</th>
                <th>工单类型</th>
                <th>当前节点</th>
                <th>工单状态</th>
                <th>提交时间</th>
                <th>变更时间</th>
                <th>工单审批</th>
            </tr>
        </thead>
        <tbody>
        {% for tic in allpage %}
        <tr>
            <td>{{ tic.ticket_id }}</td>
            <td>{{ tic.applicant }}</td>
            <td>{{ tic.ticket_name }}</td>
            <td>{{ tic.ticket_type }}</td>
            <td>{{ tic.current_node }}</td>
            <td>{{ tic.get_ticket_status_display }}</td>
            <td>{{ tic.create_time }}</td>
            <td>{{ tic.update_time }}</td>
            <td><a href="{% url "ticket_detail_approve" ticket_id=tic.ticket_id %}">审批</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}
{% block button %}
    <div class="butt_r">
        <input type="submit" class="btn btn-info btn-fill" value="提交" {{ disable }}/>
    </div>
{% endblock button %}